# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    api-web:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`)
      service: api-web

  services:
    api-web:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:9080
