# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    note:
      entryPoints:
        - web
      rule: Host(`note.notopia.localhost`)
      service: note

  services:
    note:
      loadBalancer:
        servers:
          - url: http://localhost:8081
