# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    note:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`) && PathPrefix(`/note`)
      service: note
      middlewares:
        - jwt

  services:
    note:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8081
