## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4
servers:
  - url: http://localhost:8081
    description: Local dev/mock server direct
  - url: http://localhost:8080
    description: Local dev server via gateway

info:
  description: >
    Notopia API - A comprehensive note-taking service API.
  version: 0.1.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  contact:
    name: Notopia Support
    email: kevinnitro@duck.com

tags:
  - name: note
    description: Operations related to notes management

paths:
  /api/note/notes:
    $ref: ./paths/notes.yaml
  /api/note/notes/{noteId}:
    $ref: ./paths/notes_{noteId}.yaml

components:
  securitySchemes:
    oauth2:
      $ref: ../shared/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://notopia-uit.github.io/notopia
