# vim:ft=yaml.docker-compose:
name: notopia

include:
  - ./infrastructure/authentik.yaml
  - ./infrastructure/casbin.yaml
  - ./infrastructure/dbgate.yaml
  - ./infrastructure/meilisearch.yaml
  - ./infrastructure/minio.yaml
  - ./infrastructure/redis_pub_sub.yaml
  - ./infrastructure/redpanda.yaml
  - ./infrastructure/traefik.yaml
  - ./services/note.yaml
