# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
name: notopia

include:
  - ./infrastructure/authorize.yaml
  - ./infrastructure/gateway.yaml
  - ./infrastructure/identity_provider.yaml
  - ./infrastructure/message_broker.yaml
  - ./infrastructure/object_storage.yaml
  - ./infrastructure/search.yaml
  - ./services/note.yaml

networks:
  proxy:
    name: notopia_proxy
    external: true
