# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  traefik:
    container_name: notopia-traefik
    image: traefik:3.6.7
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.web.address=:80
      - --log.level=INFO
      - --experimental.plugins.jwt.moduleName=github.com/traefik-plugins/traefik-jwt-plugin
      - --experimental.plugins.jwt.version=v0.10.0
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/dynamic:ro
    labels:
      - traefik.http.middlewares.jwt-auth.plugin.jwt.Keys=http://authentik/application/o/gateway/jwks/
      - traefik.http.middlewares.jwt-auth.plugin.jwt.Required=true
      - traefik.http.middlewares.jwt-auth.plugin.jwt.PayloadFields=exp,sub
      - traefik.http.middlewares.jwt-auth.plugin.jwt.JwtHeaders.X-JWT-User=sub
      - traefik.http.middlewares.jwt-auth.plugin.jwt.JwtHeaders.X-JWT-Email=email
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
