# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  authentik_server:
    container_name: notopia-authentik_server
    image: ghcr.io/goauthentik/server:2025.12.1
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopiauit}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER:-notopiauit}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-notopiauit}
    volumes:
      - authentik_data:/data
      # - ./custom-templates:/templates
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.rule=Host(`authentik.notopia.localhost`)
      - traefik.http.routers.authentik.entrypoints=web
      - traefik.http.services.authentik.loadbalancer.server.port=9000
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    restart: unless-stopped

  authentik_worker:
    container_name: notopia-authentik_worker
    image: ghcr.io/goauthentik/server:2025.12.1
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopiauit}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER:-notopiauit}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-notopiauit}
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD:-notopiauit}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN:-notopiauit}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik_data:/data
      # - ./certs:/certs
      # - ./custom-templates:/templates
      - ./authentik-blueprints/:/blueprints/notopia:ro
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    restart: unless-stopped
    user: root

  authentik_postgresql:
    container_name: notopia-authentik_postgresql
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_DB: ${AUTHENTIK_POSTGRESQL__NAME:-authentik}
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopiauit}
      POSTGRES_USER: ${AUTHENTIK_POSTGRESQL__USER:-notopiauit}
    volumes:
      - authentik_postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
    restart: unless-stopped

volumes:
  authentik_data:
  authentik_postgresql_data:
