# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  authentik_server:
    container_name: authentik_server
    image: ghcr.io/goauthentik/server:2025.12.1
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME:-notopia}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopia}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER:-notopia}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-notopia}
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - authentik_data:/data
      # - ./custom-templates:/templates
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    restart: unless-stopped

  authentik_worker:
    container_name: authentik_worker
    image: ghcr.io/goauthentik/server:2025.12.1
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRESQL__NAME:-notopia}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopia}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRESQL__USER:-notopia}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-notopia}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik_data:/data
      # - ./certs:/certs
      # - ./custom-templates:/templates
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    restart: unless-stopped
    user: root

  authentik_postgresql:
    container_name: authentik_postgresql
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_DB: ${AUTHENTIK_POSTGRESQL__NAME:-notopia}
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRESQL__PASSWORD:-notopia}
      POSTGRES_USER: ${AUTHENTIK_POSTGRESQL__USER:-notopia}
    volumes:
      - authentik_postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
    restart: unless-stopped

volumes:
  authentik_data:
  authentik_postgresql_data:
