# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  minio:
    container_name: notopia-minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command:
      - server
      - /data
      - --console-address=:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-notopiauit}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-notopiauit}
      MINIO_DOMAIN: minio.notopia.localhost
    volumes:
      - minio:/data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.minio.rule: Host(`minio-api.notopia.localhost`)
      traefik.http.routers.minio.entrypoints: web
      traefik.http.services.minio.loadbalancer.server.port: '9000'
      traefik.http.routers.minio-console.rule: Host(`minio.notopia.localhost`)
      traefik.http.routers.minio-console.entrypoints: web
      traefik.http.services.minio-console.loadbalancer.server.port: '9001'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
    restart: unless-stopped

  minio_bucket:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: notopia-minio_bucket
    entrypoint: > # language: sh
      /bin/sh -c '
        until (/usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER:-notopiauit} ${MINIO_ROOT_PASSWORD:-notopiauit}) do
          sleep 1;
        done
        /usr/bin/mc mb minio/notopia;
        /usr/bin/mc policy set public minio/notopia;
      '
    depends_on:
      minio:
        condition: service_healthy

volumes:
  minio:
