# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  minio:
    container_name: notopia-minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command:
      - server
      - /data
      - --console-address=:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-notopiauit}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-notopiauit}
    volumes:
      - minio:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio-api.notopia.localhost`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.rule=Host(`minio.notopia.localhost`)
      - traefik.http.routers.minio-console.entrypoints=web
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
    restart: unless-stopped

volumes:
  minio:
