# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.33
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-notopia}
    volumes:
      - meilisearch_data:/meili_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.meilisearch.rule=Host(`meilisearch.notopia.localhost`)
      - traefik.http.routers.meilisearch.entrypoints=web
      - traefik.http.services.meilisearch.loadbalancer.server.port=7700
    networks:
      - default
      - public
    restart: unless-stopped

volumes:
  meilisearch_data:
