# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.33
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-notopia}
    ports:
      - 7700:7700
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped

volumes:
  meilisearch_data:
