name: CI

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: .mise.ci.toml
  IS_PRIMARY_BRANCH: >-
    ${{
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/dev' ||
      startsWith(github.ref, 'refs/tags/v') ||
      github.base_ref == 'main' ||
      github.base_ref == 'dev'
    }}
  IS_RENOVATE: ${{ startsWith(github.head_ref, 'renovate/') }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: >-
            ${{
              (env.IS_PRIMARY_BRANCH == 'true' && env.IS_RENOVATE == 'false')
              && 'pnpm'
              || ''
            }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version-file: .tool-versions
          skip-save-cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Derive SHAs for Nx Affected
        id: set-shas
        uses: nrwl/nx-set-shas@v4

      - name: Restore Nx Cache
        uses: actions/cache/restore@v5
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ steps.set-shas.outputs.base }}

      - name: Restore Docs diagrams Cache
        uses: actions/cache/restore@v5
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install Go Dependencies
        run: go mod download

      - name: Lint & Format
        run: npx nx affected -t lint format:check --parallel=5

      - name: Test
        run: npx nx affected -t test --parallel=5 --ci

      - name: Build
        if: github.event_name != 'pull_request'
        run: npx nx affected -t build --parallel=5

      # - name: Publish Release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: npx nx release publish

      - name: Setup Git User
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npx nx affected -t deploy --parallel=3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nx
        uses: actions/cache/save@v5
        if: >-
          ${{
            env.IS_PRIMARY_BRANCH == 'true' &&
            env.IS_RENOVATE == 'false'
          }}
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ steps.set-shas.outputs.head }}

      - name: Cache Docs diagrams
        uses: actions/cache/save@v5
        if: >-
          ${{
            env.IS_PRIMARY_BRANCH == 'true' &&
            env.IS_RENOVATE == 'false'
          }}
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-${{ hashFiles('docs/src/public/diagrams/**') }}
