name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: .mise.ci.toml

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version-file: .tool-versions

      - name: Setup Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install Go Dependencies
        run: go mod download

      - name: Restore Nx Cache
        uses: actions/cache/restore@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx-

      - name: Restore Docs diagrams Cache
        uses: actions/cache/restore@v4
        with:
          path: docs/src/public/diagrams/
          key: ${{ runner.os }}-docs-diagrams-

      - name: Derive SHAs for Nx Affected
        uses: nrwl/nx-set-shas@v4

      - name: Lint & Format
        run: npx nx affected -t lint format:check --parallel=3

      - name: Test
        run: npx nx affected -t test --parallel=3 --ci

      - name: Build
        if: github.event_name != 'pull_request'
        run: npx nx affected -t build --parallel=3

      # - name: Publish Release
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: npx nx release publish

      - name: Setup Git User
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npx nx affected -t deploy --parallel=3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nx
        uses: actions/cache/save@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ hashFiles('.nx/**') }}

      - name: Cache Docs diagrams
        uses: actions/cache/save@v4
        with:
          path: docs/src/public/diagrams/
          key: ${{ runner.os }}-docs-diagrams-${{ hashFiles('docs/src/public/diagrams/**') }}
